services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U api -d db']
      interval: 5s
      timeout: 2s
      retries: 20

  api:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    networks:
      - app-network
    env_file: '.env'

volumes:
  postgres_data:
networks:
  app-network:
